# Generated by Django 2.1.4 on 2019-03-31 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(choices=[('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Shortput', 'Shortput'), ('Javelin', 'Javelin'), ('100 meter', '100 meter')], default='None', max_length=30)),
                ('first', models.CharField(max_length=30)),
                ('second', models.CharField(max_length=30)),
                ('third', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=35)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('eventname', models.CharField(choices=[('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Shortput', 'Shortput'), ('Javelin', 'Javelin'), ('100 meter', '100 meter')], default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(choices=[('High Jump', 'High Jump'), ('Long Jump', 'Long Jump'), ('Shortput', 'Shortput'), ('Javelin', 'Javelin'), ('100 meter', '100 meter')], default='None', max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('date', models.DateField(max_length=30)),
                ('time', models.TimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('location', models.CharField(default='Your Location', max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
